services:
  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BASE_URL: http://web:3000
      DOCKER: "1"
    volumes:
      - ./playwright-report:/e2e/playwright-report
    networks:
      - default
    depends_on:
      web:
        condition: service_healthy

networks:
  default:
    name: adivento_default
    external: true
